# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: app/protos/Greetings.proto for package 'rpc'

require 'grpc'
require 'app/protos/Greetings_pb'

module Rpc
  module Greetings
    class Service

      include ::GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'rpc.Greetings'

      rpc :Users, ::Rpc::Void, ::Rpc::UserResp
      rpc :Greeting, ::Rpc::GreetReq, ::Rpc::GreetResp
    end

    Stub = Service.rpc_stub_class
  end
end
