# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: app/protos/Greetings.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("app/protos/Greetings.proto", :syntax => :proto3) do
    add_message "rpc.Void" do
    end
    add_message "rpc.User" do
      optional :id, :uint32, 1
      optional :nickname, :string, 2
    end
    add_message "rpc.UserResp" do
      repeated :users, :message, 1, "rpc.User"
    end
    add_message "rpc.GreetReq" do
      optional :id, :uint32, 1
      optional :message, :string, 2
    end
    add_message "rpc.GreetResp" do
      optional :id, :uint32, 1
      optional :message, :string, 2
    end
  end
end

module Rpc
  Void = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("rpc.Void").msgclass
  User = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("rpc.User").msgclass
  UserResp = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("rpc.UserResp").msgclass
  GreetReq = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("rpc.GreetReq").msgclass
  GreetResp = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("rpc.GreetResp").msgclass
end
